### ISSUE TITLE
Missing tmlgr package for rendering to pdf from ipynb

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#102]
After following the OSX install instructions, I still cannot render to pdf from ipynb...

So using the following in R:

```
tinytex::parse_install(
   text = "! LaTeX Error: File `pdfcol.sty' not found."
   )
```

I see that `oberdiek` is now need to render pdf from ipynb:
```
tlmgr search --file --global '/pdfcol.sty'
tlmgr install oberdiek
```

After installing that I could render pdf from ipynb. We should add this to our install instructions (`tlmgr install oberdiek`).

**Comment by joelostblom** [comment]
Done in #107

**Comment by joelostblom** [comment]
Two students reported this year that this is still happening and it was only resolved by running a command from within R instead of `tlmgr` from the command line:

> I tried tlmgr install pdfcol in my terminal and it still says tlmgr install: package already present: oberdiek like what I tried the other day. But I did follow what this link says https://github.com/UBC-MDS/UBC-MDS.github.io/issues/102, and tried in R:
tinytex::parse_install(
   text = "! LaTeX Error: File `pdfcol.sty' not found."
   )
then R started to execute tlmgr install pdfcol and I got a message saying that tlmgr: package log updated and tlmgr: command log updated  . After this I was able to export pdf with no problem.

Two students reported that `tlmgr install pdfcol` did work for them so we should still add that to the instruction

**Comment by joelostblom** [comment]
I didn't hear any complaints about this in the last two years so closing. cc @chendaniely so that you have seen it in case it comes up again this year.

**Comment by chendaniely** [comment]
I don't think we came across this issue in 310 either. Pdf stuff was weird sometimes but it was mostly docker.

But there are ARM RStudio docker images now, so hopefully no more issues?
