### ISSUE TITLE
nbconvert v7.0.0

### ISSUE THREAD

**Issue by flor14** [UBC-MDS/UBC-MDS.github.io-jekyll#149]
@joelostblom 

There is a new release of `nbconvert` right now that the students are installing everything. Apparently this breaks the script that we are using to check the installation as the version changes to 7.0.0.

https://github.com/jupyter/nbconvert/releases

I think the best thing to do is update the script, EXCEPT we find a good reason to not update this among the new changes introduced.

**Comment by joelostblom** [comment]
Fixed in https://github.com/UBC-MDS/UBC-MDS.github.io/commit/6d0ab86fd2faf716d05c1bceb7fdb058233a7e90 to only allow 7 now. One drawback could be that some students could still be getting 6.x for some reason and ideally we would probably allow for both v6 and v7, but it would take me longer to fix that so please re-open this issue if there are problems and I will try to allow for both 6 and 7.
