### ISSUE TITLE
About the MDS needs to be updated

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#33]
Our About the MDS page needs updating. Specifically we need to:

- [ ] state that Stat & CS run the MDS, and we have been doing so since 2015 (currently it says we are planning to run this program
- [ ] have the first paragraph be about MDS instead of UBC (maybe just make the UBC stuff a block quote somewhere on the page
- [ ] link to our public materials from there, as well as our admissions page and our Alumni stories
- [ ] perhaps this is where our people (instructors and staff) should be listed/posted/linked to

**Comment by mgelbart** [comment]
@ttimbers I think it would be fine to just remove the about page, since all the info we want is already in other places. For reference, here is a link to the [old about page](https://github.com/UBC-MDS/UBC-MDS.github.io/blob/df3a9f0236600be41ae443ad4dab3f3d7b1605da/about.md). Are you fine leaving this out? I adding a link to our public materials from the vision, and we could potentially throw in a couple more links, especially once the new People page is ready?

**Comment by ttimbers** [comment]
This has now been done.
