### ISSUE TITLE
Docs for how to make the R things work on Windows:

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#68]
- [Make Rscrip (at the command line) see the correct directory to load libraries](https://github.ubc.ca/MDS-2019-20/DSCI_522_dsci-workflows_students/issues/4)
- [Set Git Bash as terminal in RStudio on Windows](https://github.ubc.ca/MDS-2019-20/DSCI_522_dsci-workflows_students/issues/12)

A couple of notes:
- Make Jupyter use the CRAN version of R. This should happen automatically after installing the IRkernel. However the one gotcha is if students install R with `conda`, then this clobbers the `PATH`. Solution for this is to delete `conda`'s version of R and Rscript.

cc @joelostblom

**Comment by joelostblom** [comment]
Thank you! I will update to set the env var to what you suggested, I followed up with a comment on this in  the PR also.

Regarding Git bash, this was set by default for me in RStudio.

Regarding jupyter's R version, this should not be a problem since for R I prepend the its location to so it will be in front of conda even if conda's R is isntalled (I checked the R bin folder and all those executables are so R specific that it makes sense to prepend in my opinion).

**Comment by ttimbers** [comment]
FYI - I am doing a more thorough review right now while I walk through this on my machine. Maybe you want to pause working on this until I am done?

**Comment by joelostblom** [comment]
Sounds good!

**Comment by joelostblom** [comment]
Closed by #66
